config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root "kittens#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]

  # GET /kittens or /kittens.json
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  # GET /kittens/1 or /kittens/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  # GET /kittens/new
  def new
    @kitten = Kitten.new
  end

  # GET /kittens/1/edit
  def edit
  end

  # POST /kittens or /kittens.json
  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to kitten_url(@kitten), notice: "Kitten was successfully created." }
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kittens/1 or /kittens/1.json
  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to kitten_url(@kitten), notice: "Kitten was successfully updated." }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kittens/1 or /kittens/1.json
  def destroy
    @kitten.destroy

    respond_to do |format|
      format.html { redirect_to kittens_url, notice: "Kitten was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kitten_params
      params.fetch(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: kitten) do |form| %>
  <% if kitten.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% kitten.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.number_field :age, in: 1..30, required: true %>
  </div>
  <div>
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness, in: 1..10, required: true %>
  </div>
  <div>
    <%= form.label :softness %>
    <%= form.number_field :softness, in: 1..10, required: true %>
  </div>
  <div>
    <%= form.submit %>
  </div>

  <br>
<% end %>

app/views/kittens/_kitten.html.erb
<div id="<%= dom_id kitten %>">
  <div>Name: <%= kitten.name %></div>
  <div>Age: <%= kitten.age %></div>
  <div>Cuteness: <%= kitten.cuteness %></div>
  <div>Softness: <%= kitten.softness %></div>
</div>

app/views/kittens/edit.html.erb
<h1>Editing kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Show this Kitten", @kitten %> |
  <%= link_to "Back to Kittens", kittens_path %>

  <%= button_to "Delete Kitten", @kitten, method: :delete %>
</div>

app/views/kittens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Kittens</h1>

<div id="kittens">
  <% @kittens.each do |kitten| %>
    <%= render kitten %>
    <p>
      <%= link_to "Show Kitten", kitten %> | 
      <%= link_to "Edit Kitten", edit_kitten_path(kitten)%>
      <%= button_to "Delete Kitten", kitten, method: :delete %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Back to All Kittens", kittens_path %>
</div>

app/views/kittens/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kitten %>

<div>
  <%= link_to "Edit this Kitten", edit_kitten_path(@kitten) %> |
  <%= link_to "Back to All Kittens", kittens_path %>

  <%= button_to "Delete Kitten", @kitten, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>